### ISSUE TITLE
API: [SPIKE] Pydantic validations

### ISSUE THREAD

**Issue by mariogarridopt** [mariogarridopt/bookit#13]
As @prashanthreddykallem show us on #12, there is a lib called [Pydantic](https://docs.pydantic.dev/latest/) that could help us validate the model data.

> [SPIKE]: A task that is created in order to research a question or resolve a problem. Spikes focus on gathering information and finding answers to a questions, rather than producing a shippable product.

Let's discuss how [Pydantic](https://docs.pydantic.dev/latest/) might help this API and how it should be implemented.

**Acceptance criteria:**
At the end of this spike a PR must be created with a refactor of the existing code with [Pydantic](https://docs.pydantic.dev/latest/) implemented, or, we diced that [Pydantic](https://docs.pydantic.dev/latest/) will not help the project.

**Comment by mariogarridopt** [comment]
Since we have the schema of the database already on the model files maybe we can implement Pydantic there, at list the validations have to be created there, the inheritance of Pydantic probably can be done at the BaseModel that is then enherited to every model.

**Comment by mariogarridopt** [comment]
@prashanthreddykallem can you please review the implementation on #14 ?

**Comment by prashanthreddykallem** [comment]
Hey Mario,

Sorry for the late reply. I get your point regarding schema and model code duplication. I am trying to think of a solution for a scenario where where the fields in the model many not be present in the schema and vice versa. Schemas also help in validating the output of the particular api.

When it comes to pydantic, it helps in validation of input and output of the api. If not for pydantic what is your proposed solution for validating the inputs of the json as mentioned in issue #7? We could write our own validation code but pydantic simplifies it and makes it easy for us. 


Thank you

**Comment by mariogarridopt** [comment]
Feature implemented on #14
