### ISSUE TITLE
bug: Login using GET is dangerous

### ISSUE THREAD

**Issue by mariogarridopt** [mariogarridopt/bookit#5]
At the moment, the login endpoint (`auth/token`) is using `/GET` as the http method.

This is not secure because URL's can be sniffed and passing the password in plain text hover URL Query is not a good idea.

This should be changed to a `POST` with the username and passwords sent via JSON BODY.
The request will look like this:
```bash
curl --request GET \
  --url http://127.0.0.1:8181/auth/token \
  --data '{
	"username": "admin",
	"password": "admin"
}'
```

**Comment by duongyennhi** [comment]
Hello Can I help you?

**Comment by mariogarridopt** [comment]
Yes
Let me know if you have any questions.
When ready, please submit a Pull Request

Thanks for the interest ^^
