### ISSUE TITLE
feat: Update user data endpoints

### ISSUE THREAD

**Issue by mariogarridopt** [mariogarridopt/bookit#6]
Allow users to update their data.

At the moment at `api/controllers/auth_controller.py` we have two methods that need completion:
- `update_my_data(user_id: int)` endpoint: `PUT /auth`
- `update_data(admin_id: int, user_id: int)` endpoint: `PUT /auth/manage/<int:user_id>`

Those should allow the users to edit data on the `auth` database.

The endpoint should return a json with the edited data, like:
```json
{
	"active": 1,
	"created_at": "Wed, 01 Nov 2023 00:40:49 GMT",
	"id": 1,
	"role": "admin",
	"username": "mr-soup"
}
```

Make use of the existing `Auth.update` method if possible.

**Comment by Datremar** [comment]
A few questions

- Do you really have to return password field in response?
- If so, I presume, you need it hashed?

**Comment by mariogarridopt** [comment]
No, the password shouldn't be part of the response, this issue was created before #15. I will edit the issue now.

**Comment by Datremar** [comment]
> No, the password shouldn't be part of the response, this issue was created before #15. I will edit the issue now.

Thanks for the clarification!
