### ISSUE TITLE
feat: Add new user

### ISSUE THREAD

**Issue by mariogarridopt** [mariogarridopt/bookit#7]
Allow users to update their data.

At `api/controllers/auth_controller.py` we have a method named `add_user(admin_id: int)` on the endpoint `POST /manageh` that should allow users to be created.

The endpoint should receive a user as JSON on the body like this:
```bash
curl --request POST \
  --url http://127.0.0.1:8181/auth/manage \
  --header 'Authorization: Bearer 1btIC8Z0a84_ASsejhmLxA' \
  --header 'Content-Type: application/json' \
  --data '{
	"active": 1,
	"password": "my_cool_password",
	"role": "admin",
	"username": "admin_v2"
}'
```

And if there are no errors on the insert reply to the request with a JSON of the inserted user full data like:
```json
{
	"active": 1,
	"role": "admin",
	"username": "admin_v2",
	"id": 6,
	"created_at": "Wed, 01 Nov 2023 00:40:49 GMT",
}
```

Make use of the existing `Auth.insert` method if possible.

Protect against duplicated usernames

**Comment by prashanthreddykallem** [comment]
Hey Mario,

I have one suggestion regarding this issue, Is it safe to send the user back the password field? I think we should remove that from the response JSON

**Comment by mariogarridopt** [comment]
I agree, there is no need to send the user his hashed password, lets remove that.
